/**
 * Common envelope fields shared by WSS messages and selected IPC payloads.
 * Keeping these stable lets clients and brokers evolve payloads independently.
 */
import { z } from 'zod';

/** Current wire protocol version for WSS broker messages. */
export const PROTOCOL_VERSION = 1 as const;

export const protocolVersionSchema = z.literal(PROTOCOL_VERSION);

/** Opaque request correlation id generated by the desktop client. */
export const requestIdSchema = z.string().uuid();

/**
 * Stable ticket identity used across local cache, sanitizer revisions, and WSS.
 * Format: freshdeskHost + ":" + numeric ticket id.
 */
export const ticketKeySchema = z
  .string()
  .min(3)
  .max(256)
  .regex(/^[a-z0-9.-]+:\d+$/i, 'ticketKey must be host:ticketId');

export const isoTimestampSchema = z.string().datetime({ offset: true });

/** Maximum inbound/outbound WSS JSON payload size (bytes) for prototype safety. */
export const MAX_WSS_MESSAGE_BYTES = 256_000;

export type ProtocolVersion = z.infer<typeof protocolVersionSchema>;
export type RequestId = z.infer<typeof requestIdSchema>;
export type TicketKey = z.infer<typeof ticketKeySchema>;
